ALTER TYPE "OtpType" ADD VALUE IF NOT EXISTS 'ACCOUNT_CLOSE';
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "deactivatedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "deactivatedAt" TIMESTAMP(3), ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
